fix = true
unsafe-fixes = true
include = ["pyproject.toml", "src/**/*.py", "bin/**/*.py", "snippets/**/*.py"]
line-length = 120

[lint]
select = ["E4", "E7", "E9", "F", "B", "A", "I", "UP"]

[format]
quote-style = "double"  # use double quotes for strings
